## NumPy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.



In [6]:
# import 
import numpy as np

### Creating array using numpy

In [13]:
# creating 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [29]:
# reshaping array
arr2=np.array([1,2,3,4,5])
print(arr2.reshape(1,5))
print(arr2.shape)

reshaped = arr2.reshape(1, 5)
print(reshaped)  
print(reshaped.shape)  

# arr1 and arr2 are initially created as 1D arrays, and their shape is (5,).
# When you reshape arr2 to (1, 5) and check the shape of arr2, it still remains (5,) 
# because the reshape operation does not modify the original array—it returns a new array with the specified shape.

[[1 2 3 4 5]]
(5,)
[[1 2 3 4 5]]
(1, 5)


In [33]:
# creating 2D array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,3]])
print(arr2)
print(arr2.shape) # (2 rows 5 columns)

[[1 2 3 4 5]
 [6 7 8 9 3]]
(2, 5)


## arrays with inbuilt functions

In [40]:
np.arange(0,10,2) #Return evenly spaced values within a given interval.

array([0, 2, 4, 6, 8])

In [46]:
np.ones((3,4))  #return a new array of given shape and type, filled with ones.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
## Attributes of nummpy array

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [52]:
### numpy vectorized operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [56]:
 ## universal function

arr=np.array([2,3,4,5,6])
# square root
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


## array slicing and indexing

In [125]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [4,6,7,5,8]])
print("array:\n",arr)

array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 4  6  7  5  8]]


In [65]:
#print element from 2nd row 3rd columna
arr[1][2]

8

In [83]:
arr[1,1:][1,] #arr[1,1:] results in a 1D array: [7, 8, 9, 10] ; 
             #Since arr[1,1:] is now a 1D array, the [1,] index simply selects the second element (at index 1) of this array.

8

In [97]:
#Row slicing (1:): Selects rows from index 1 onwards.
#Column slicing (:3): Selects the first three columns of the selected rows.
arr[1:,:3] 

array([[6, 7, 8],
       [4, 6, 7]])

In [117]:
#Row slicing (0:2): Selects rows from index 0 to 2 (excluding 2).
#Column slicing (-2:): Selects the last two columns of the selected rows.
arr[0:2,-2:]

array([[ 4,  5],
       [ 9, 10]])

In [127]:
## modify the array 
arr[1:,0:3]=100
arr

array([[  1,   2,   3,   4,   5],
       [100, 100, 100,   9,  10],
       [100, 100, 100,   5,   8]])

## statistical concepts

In [134]:
data = np.array([[1,2,3,4,5], [6,7,8,9,10], [4,6,7,5,8]])

mean = np.mean(data)
std_dev = np.std(data)

# normalise the data
normalised_data= (data-mean)/std_dev
print(normalised_data)

# data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

[[-1.87082869 -1.46993683 -1.06904497 -0.6681531  -0.26726124]
 [ 0.13363062  0.53452248  0.93541435  1.33630621  1.73719807]
 [-0.6681531   0.13363062  0.53452248 -0.26726124  0.93541435]]
Mean: 5.666666666666667
Median: 6.0
Standard Deviation: 2.4944382578492945
Variance: 6.222222222222223
